// import {Food} from './app/shared/models/food';
// import { Tag } from './app/shared/models/tag';

export const sample_foods: any[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 200,
    discription:'Pizza is a delicious, cheesy, and customizable dish with various toppings and crust styles.',
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/f1.png',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'burger',
    price: 170,
    cookTime: '20-30',
    discription:'A burger is a tasty, juicy sandwich with a grilled patty, fresh toppings, and a bun. ',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/f2.png',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Delicious Pizza',
    cookTime: '10-20',
    price: 100,
    discription:'Pizza is a delicious, cheesy, and customizable dish with various toppings and crust styles.',
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/f3.png',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'4',
    name: 'Delicious Pasta',
    price: 130,
    cookTime: '10-15',
    discription:'Pasta is a versatile Italian dish made from wheat, served with sauces, meats, or vegetables.',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/f4.png',
    tags: ['FastFood', 'Pasta'],
  },
  {
    id:'5',
    name: 'French Fries',
    price: 100,
    cookTime: '15-20',
    discription:'French fries are crispy, golden potato sticks, fried to perfection and often salted.',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/f5.png',
    tags: ['FastFood', 'Fries'],
  },
  {
    id:'6',
    name: 'Delicious Pizza',
    price: 300,
    cookTime: '40-50',
    discription:'Pizza is a delicious, cheesy, and customizable dish with various toppings and crust styles.',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/f6.png',
    tags: ['SlowFood', 'pizza'],
  },
  {
    id:'7',
    name: 'Tasty Burger',
    price: 90,
    cookTime: '40-50',
    discription:'A burger is a tasty, juicy sandwich with a grilled patty, fresh toppings, and a bun. ',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/f7.png',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'8',
    name: 'Tasty Burger',
    price: 80,
    cookTime: '40-50',
    discription:'A burger is a tasty, juicy sandwich with a grilled patty, fresh toppings, and a bun. ',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/f8.png',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'9',
    name: 'Delicious Pasta',
    price: 200,
    cookTime: '40-50',
    discription:'Pasta is a versatile Italian dish made from wheat, served with sauces, meats, or vegetables.',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/f9.png',
    tags: ['FastFood', 'pasta', 'Lunch'],
  },
]
export const sample_users: any[] = [
  {
    name: 'admin',
    email: 'admin@gmail.com',
    password: '12345',
    address: 'admin',
    isAdmin: true,
  },
  

];


export const sample_tags:any[] = [
  { name: 'All', count: 9 },
  { name: 'FastFood', count: 9 },
  { name: 'Pizza', count: 3 },
  { name: 'burger', count: 3 },
  { name: 'Fries', count: 1 },
  { name: 'pasta', count: 2 },
]
